#!/usr/bin/env bash
# shellcheck disable=SC2154,SC2034

# REPORT RESULTS IN TEMPORARY FILE

case "${retval:-0}" in
	"$DIALOG_OK")
		RESULT="$(cat "$tempfile")";;
	"$DIALOG_CANCEL")
		exit "$DIALOG_CANCEL";;
	"$DIALOG_ESC")
		if [[ -s "$tempfile" ]]; then
			cat "$tempfile"
		else
			exit "$DIALOG_ESC"
		fi;;
esac
