#!/usr/bin/env bash
# shellcheck disable=SC2154,SC2034

# REPORT BUTTON ONLY - NOT $RESULT

case ${retval:-0} in
	"$DIALOG_OK")
		echo "YES";;
	"$DIALOG_CANCEL")
		echo "NO";;
	"$DIALOG_ESC")
		echo "ESC pressed";;
esac
