#!/usr/bin/env bash

# REPORT BUTTON ONLY - NOT $RESULT

case ${retval:-0} in
	"$DIALOG_OK")
		echo "OK";;
	"$DIALOG_CANCEL")
		echo "NO";;
	"$DIALOG_HELP")
		echo "Help pressed";;
	"$DIALOG_EXTRA")
		echo "Extra button pressed";;
	"$DIALOG_ITEM_HELP")
		echo "Item-help button pressed";;
	"$DIALOG_ERROR")
		echo "ERROR!";;
	"$DIALOG_ESC")
		echo "ESC pressed";;
esac
