#!/usr/bin/env bash
# shellcheck disable=SC2154,SC2034

# REPORT RESULTS FROM EDITING

case "${retval:-0}" in
	"$DIALOG_OK")
		diff -c "${input:-input}" "${output:-output}";;
	"$DIALOG_CANCEL")
		exit "$DIALOG_CANCEL";;
	"$DIALOG_ESC")
		if [[ -s "$output" ]]; then
			diff -c "${input:-input}" "${output:-output}"
		else
			exit "$DIALOG_ESC"
		fi;;
esac
