#!/usr/bin/env bash

# REPORT RESULTS PASSED IN STRING $RESULT

case "${retval:-0}" in
	"$DIALOG_OK")
		echo "Result: $RESULT";;
	"$DIALOG_CANCEL")
		echo "Cancelled";;
	"$DIALOG_ESC")
		if [[ -n "$RESULT" ]]; then
			echo "$RESULT"
		else
			echo "ESC pressed"
		fi;;
esac
