#!/usr/bin/env bash

declare -gx DIALOG=dialog

declare -gx DIALOG_OK=0
declare -gx DIALOG_CANCEL=1
declare -gx DIALOG_HELP=2
declare -gx DIALOG_EXTRA=3
declare -gx DIALOG_ITEM_HELP=4
declare -gx DIALOG_ERROR=254
declare -gx DIALOG_ESC=255

declare -gx SIG_NONE=0
declare -gx SIG_HUP=1
declare -gx SIG_INT=2
declare -gx SIG_QUIT=3
declare -gx SIG_KILL=9
declare -gx SIG_TERM=15
