#!/usr/bin/env bash
# shellcheck disable=SC1091,SC2034

. /usr/local/lib/dd/setup-vars

DD="$(date +%d)"
MM="$(date +%m)"
YY="$(date +%y)"
YYYY="$(date +%Y)"

RESULT=$($DIALOG --stdout \
	--ok-label "${OK_LABEL:-OK}" \
	--cancel-label "${CANCEL_LABEL:-Cancel}" \
	--backtitle "${DIALOG_BACKTITLE}" \
	--title "${DIALOG_TITLE}" --clear "$@" \
	--calendar "${DIALOG_TEXT}" "${HEIGHT:-15}" "${WIDTH:-50}" "${DIALOG_DAY:-$DD}" "${DIALOG_MONTH:-$MM}" "${DIALOG_YEAR:-$YYYY}" 3>&1 1>&2 2>&3)

retval=$?

. /usr/local/lib/dd/read-result
