#!/usr/bin/env bash
# shellcheck disable=SC1091,SC2034

. /usr/local/lib/dd/setup-vars
. /usr/local/lib/dd/setup-edit

RESULT=$($DIALOG --ok-label "${OK_LABEL:-OK}" \
	--cancel-label "${CANCEL_LABEL:-Cancel}" \
	--backtitle "${DIALOG_BACKTITLE}" \
	--title "${DIALOG_TITLE}" --clear "$@" \
	--editbox "${DIALOG_INPUT:-$input}" "${HEIGHT:-15}" "${WIDTH:-50}" 2>"$output")

retval=$?

. /usr/local/lib/dd/report-edit
