#!/usr/bin/env bash
# shellcheck disable=SC1091,SC2034

. /usr/local/lib/dd/setup-vars

retval=0

while [[ "$retval" -ne 1 ]] && [[ "$retval" -ne 254 ]]
do
	exec 3>&1
	RESULT=$($DIALOG --ok-label "${OK_LABEL:-OK}" \
		--cancel-label "${CANCEL_LABEL:-Cancel}" \
		--help-label "${HELP_LABEL:-Help}" \
		--backtitle "${DIALOG_BACKTITLE}" \
		--title "${DIALOG_TITLE}" --clear "$@" \
		--form "${DIALOG_TEXT}" "${HEIGHT:-15}" "${WIDTH:-50}" "${LIST_HEIGHT:-5}" \
		"${DIALOG_OPTIONS[@]}" 2>&1 1>&3)
	retval=$?
	exec 3>&-

	case "$retval" in
		"$DIALOG_CANCEL")
			"$DIALOG" --clear \
				--yesno "Really quit?" 10 30
			case $? in
				"$DIALOG_OK")
					break
					;;
				"$DIALOG_CANCEL")
					retval=99
					;;
			esac
			;;
		"$DIALOG_OK")
			"$DIALOG" --clear \
				--title "FORM DATA" --no-collapse --cr-wrap \
				--msgbox "$RESULT" 10 40
			;;
		"$DIALOG_HELP")
			echo "HELP"
			exit
			;;
		"$DIALOG_ERROR")
			echo "ERROR"
			exit
			;;
		"$DIALOG_ESC")
			echo "ESC"
			exit
			;;
		*)
			echo "Code returned was '$retval'"
			exit
			;;
	esac
done
