#!/usr/bin/env bash
# shellcheck disable=SC1091,SC2034,SC2188
# ==================================================================
# form-demo
# ==================================================================
# Dialog Dojo Dialog Box
#
# File:         form-demo
# Author:       Ragdata
# Date:         15/09/2023
# License:      MIT License
# Copyright:    Copyright © 2023 Darren (Ragdata) Poulton
# ==================================================================
<<manual
"
--form text height width formheight [ label y x item y x flen ilen ] ...

The form dialog displays a form consisting of labels and fields,
which are positioned on a scrollable window by coordinates given
in the script.  The field length flen and input-length ilen tell
how  long the field can be.  The former defines the length shown
for a selected field, while the latter defines  the  permissible
length of the data entered in the field.

o   If  flen is zero, the corresponding field cannot be altered.
    and the contents  of  the  field  determine  the  displayed-
    length.

o   If  flen  is  negative,  the  corresponding  field cannot be
    altered, and the negated  value  of  flen  is  used  as  the
    displayed-length.

o   If ilen is zero, it is set to flen.

Use  up/down  arrows  (or  control/N, control/P) to move between
fields.  Use tab to move between windows.

On exit, the contents of the form-fields are written to dialogs
output,  each  field  separated  by a newline.  The text used to
fill non-editable fields (flen  is  zero  or  negative)  is  not
written out.
"
manual
# ==================================================================
. /usr/local/lib/dd/setup-vars

retval=0

while [[ "$retval" -ne 1 ]] && [[ "$retval" -ne 254 ]]
do
	RESULT=$("$DIALOG" --ok-label "${OK_LABEL:-OK}" \
		--cancel-label "${CANCEL_LABEL:-Cancel}" \
		--help-label "${HELP_LABEL:-Help}" \
		--backtitle "${DIALOG_BACKTITLE}" \
		--title "${DIALOG_TITLE}" --clear "$@" \
		--form "${DIALOG_TEXT}" "${HEIGHT:-15}" "${WIDTH:-50}" "${LIST_HEIGHT:-5}" \
		"${DIALOG_OPTIONS[@]}" 3>&1 1>&2 2>&3)
	retval=$?
	case "$retval" in
		"$DIALOG_CANCEL")
			"$DIALOG" --clear \
				--yesno "Really quit?" 10 30
			case $? in
				"$DIALOG_OK")
					break
					;;
				"$DIALOG_CANCEL")
					retval=99
					;;
			esac
			;;
		"$DIALOG_OK")
			"$DIALOG" --clear \
				--title "FORM DATA" --no-collapse --cr-wrap \
				--msgbox "$RESULT" 10 40
			;;
		"$DIALOG_HELP")
			echo "HELP"
			exit
			;;
		"$DIALOG_ERROR")
			echo "ERROR"
			exit
			;;
		"$DIALOG_ESC")
			echo "ESC"
			exit
			;;
		*)
			echo "Code returned was '$retval'"
			exit
			;;
	esac
done
