#!/usr/bin/env bash
# shellcheck disable=SC1091,SC2034,SC2188
# ==================================================================
# infobox
# ==================================================================
# Dialog Dojo Dialog Box
#
# File:         infobox
# Author:       Ragdata
# Date:         16/09/2023
# License:      MIT License
# Copyright:    Copyright © 2023 Darren (Ragdata) Poulton
# ==================================================================
<<manual

--infobox text height width

An  info box is basically a message box.  However, in this case,
dialog will exit immediately after displaying the message to the
user.   The screen is not cleared when dialog exits, so that the
message will remain on the screen until the calling shell script
clears  it  later.   This  is useful when you want to inform the
user that some operations are carrying on that may require  some
time to finish.

On  exit,  no  text  is  written to dialog's output.  An OK exit
status is returned.

manual
# ==================================================================
. /usr/local/lib/dd/setup-vars

left="${COUNT:-10}"

while [[ "$left" -ne 0 ]]
do
	"$DIALOG" sleep 1 \
		--title "${DIALOG_TITLE:-'INFO BOX'}" "$@" \
		--infobox "${DIALOG_TEXT}\n\nClosing in $left secs" "${HEIGHT:-15}" "${WIDTH:-50}"
		left=$((left - 1))
done
