#!/usr/bin/env bash
# shellcheck disable=SC1091,SC2034,SC2188
# ==================================================================
# inputbox
# ==================================================================
# Dialog Dojo Dialog Box
#
# File:         inputbox
# Author:       Ragdata
# Date:         15/09/2023
# License:      MIT License
# Copyright:    Copyright © 2023 Darren (Ragdata) Poulton
# ==================================================================
<<manual
"
--inputbox text height width [init]

An input box is useful when  you  want  to  ask  questions  that
require  the  user  to input a string as the answer.  If init is
supplied it is  used  to  initialize  the  input  string.   When
entering  the  string, the backspace, delete and cursor keys can
be used to correct typing errors.  If the input string is longer
than  can  fit  in  the  dialog  box,  the  input  field will be
scrolled.

On exit, the input string will be printed on dialog's output.
"
manual
# ==================================================================
. /usr/local/lib/dd/setup-vars

RESULT=$("$DIALOG" --ok-label "${OK_LABEL:-OK}" \
	--cancel-label "${CANCEL_LABEL:-Cancel}" \
	--backtitle "${DIALOG_BACKTITLE}" \
	--title "${DIALOG_TITLE}" --cr-wrap --cr-wrap --clear "$@" \
	--inputbox "\n${DIALOG_TEXT}\n" "${HEIGHT:-15}" "${WIDTH:-50}" "${DIALOG_INIT}" 3>&1 1>&2 2>&3)
