#!/usr/bin/env bash
# shellcheck disable=SC1091

. ./src/etc/dlg/setup-vars
. ./src/etc/dlg/setup-tempfile

RESULT=$($DIALOG --ok-label "${OK_LABEL:-OK}" \
	--cancel-label "${CANCEL_LABEL:-Cancel}" \
	--backtitle "${DIALOG_BACKTITLE}" \
	--title "${DIALOG_TITLE}" --clear "$@" \
	--inputbox "${DIALOG_TEXT}" "${HEIGHT:-15}" "${WIDTH:-50}" "${DIALOG_INIT}" 3>&1 1>&2 2>&3)

retval=$?

. ./src/etc/dlg/read-result
