#!/usr/bin/env bash
# shellcheck disable=SC1091,SC2034,SC2188
# ==================================================================
# msgbox
# ==================================================================
# Dialog Dojo Dialog Box
#
# File:         msgbox
# Author:       Ragdata
# Date:         15/09/2023
# License:      MIT License
# Copyright:    Copyright © 2023 Darren (Ragdata) Poulton
# ==================================================================
<<manual
"
--msgbox text height width

A message box is  very  similar  to  a  yes/no  box.   The  only
difference  between  a  message  box  and a yes/no box is that a
message box has only a single  OK  button.   You  can  use  this
dialog  box  to display any message you like.  After reading the
message, the user can press the ENTER key so  that  dialog  will
exit and the calling shell script can continue its operation.

If  the message is too large for the space, dialog may allow you
to scroll it, provided that the underlying curses implementation
is  capable  enough.  In this case, a percentage is shown in the
base of the widget.

On exit, no text is written to dialog's output.   Only  an  'OK'
button  is  provided  for  input,  but an ESC exit status may be
returned.
"
manual
# ==================================================================
. /usr/local/lib/dd/setup-vars

RESULT=$("$DIALOG" --ok-label "${OK_LABEL:-OK}" \
	--cancel-label "${CANCEL_LABEL:-Cancel}" \
	--backtitle "${DIALOG_BACKTITLE}" \
	--title "${DIALOG_TITLE}" --cr-wrap --clear "$@" \
	--msgbox "\n${DIALOG_TEXT}\n" "${HEIGHT:-15}" "${WIDTH:-50}" 3>&1 1>&2 2>&3)
