#!/usr/bin/env bash
# shellcheck disable=SC1091,SC2034,SC2188
# ==================================================================
# passwordform
# ==================================================================
# Dialog Dojo Dialog Box
#
# File:         passwordform
# Author:       Ragdata
# Date:         15/09/2023
# License:      MIT License
# Copyright:    Copyright © 2023 Darren (Ragdata) Poulton
# ==================================================================
<<manual

--passwordform text height width formheight [ label y x item y x flen ilen ] ...

This  is  identical  to  --form  except that all text fields are
treated as password widgets rather than inputbox widgets.

manual
# ==================================================================
. /usr/local/lib/dd/setup-vars
. /usr/local/lib/dd/dft-std

retval=0

while [[ "$retval" -ne 1 ]] && [[ "$retval" -ne 254 ]]
do
	RESULT=$("$DIALOG" "${DIALOG_OPTS}" \
		--passwordform "${DIALOG_TEXT}" "${HEIGHT:-15}" "${WIDTH:-50}" "${LIST_HEIGHT:-5}" \
		"${DIALOG_ITEMS[@]}" 3>&1 1>&2 2>&3)
	retval=$?
	. /usr/local/lib/dd/handle-result-nohelp
done
