#!/usr/bin/env bash
# shellcheck disable=SC1091,SC2034,SC2188
# ==================================================================
# passwordbox
# ==================================================================
# Dialog Dojo Dialog Box
#
# File:         passwordbox
# Author:       Ragdata
# Date:         15/09/2023
# License:      MIT License
# Copyright:    Copyright © 2023 Darren (Ragdata) Poulton
# ==================================================================
<<manual
"
--passwordbox text height width [init]

A password box is similar to an input box, except that the  text
the user enters is not displayed.  This is useful when prompting
for passwords or other sensitive information.  Be aware that  if
anything is passed in 'init', it will be visible in the system's
process table to casual snoopers.  Also, it is very confusing to
the  user  to  provide  them with a default password they cannot
see.  For these reasons, using  'init'  is  highly  discouraged.
See '--insecure' if you do not care about your password.

On exit, the input string will be printed on dialog's output.
"
manual
# ==================================================================
. /usr/local/lib/dd/setup-vars

RESULT=$("$DIALOG" --ok-label "${OK_LABEL:-OK}" \
	--cancel-label "${CANCEL_LABEL:-Cancel}" \
	--backtitle "${DIALOG_BACKTITLE}" \
	--title "${DIALOG_TITLE}" --cr-wrap --clear "$@" \
	--passwordbox "${DIALOG_TEXT}" "${HEIGHT:-15}" "${WIDTH:-50}" 3>&1 1>&2 2>&3)
