#!/usr/bin/env bash
# shellcheck disable=SC1091,SC2034,SC2188
# ==================================================================
# passwordform-demo
# ==================================================================
# Dialog Dojo Dialog Box
#
# File:         passwordform-demo
# Author:       Ragdata
# Date:         15/09/2023
# License:      MIT License
# Copyright:    Copyright © 2023 Darren (Ragdata) Poulton
# ==================================================================
<<manual
"
--passwordform text height width formheight [ label y x item y x flen ilen ] ...

This  is  identical  to  --form  except that all text fields are
treated as password widgets rather than inputbox widgets.
"
manual
# ==================================================================
. /usr/local/lib/dd/setup-vars

retval=0

while [[ "$retval" -ne 1 ]] && [[ "$retval" -ne 254 ]]
do
	exec 3>&1
	RESULT=$("$DIALOG" --ok-label "Submit" --title "Mixed Form Demo" \
		--backtitle "DIALOG DOJO DEMOS" --insecure "$@" \
		--passwordform "Here's an idea of how you can use this dialog:" 20 50 0 \
		"Username		:" 1 1 "Ragdata" 	1 20 10 0 2 \
		"Password		:" 2 1 ""			2 20  8 0 1 \
		"Password Again	:" 3 1 ""			3 20  8 0 1 \
		"HOME			:" 4 1 "Cisco"		4 20 40 0 0 2>&1 1>&3)
	retval=$?
	exec 3>&-
	case "$retval" in
		"$DIALOG_CANCEL")
			"$DIALOG" --clear \
				--yesno "Really quit?" 10 30
			case $? in
				"$DIALOG_OK")
					break
					;;
				"$DIALOG_CANCEL")
					retval=99
					;;
			esac
			;;
		"$DIALOG_OK")
			"$DIALOG" --clear \
				--no-collapse --cr-wrap \
				--msgbox "Form Data:\n\
				$RESULT" 10 40
			;;
		"$DIALOG_HELP")
			echo "HELP"
			exit
			;;
		*)
			echo "Code returned was '$retval'"
			exit
			;;
	esac
done
