#!/usr/bin/env bash
# shellcheck disable=SC1091,SC2034,SC2188
# ==================================================================
# programbox-demo
# ==================================================================
# Dialog Dojo Dialog Box
#
# File:         programbox-demo
# Author:       Ragdata
# Date:         15/09/2023
# License:      MIT License
# Copyright:    Copyright © 2023 Darren (Ragdata) Poulton
# ==================================================================
<<manual

--programbox text height width
--programbox height width

A  programbox  is  very  similar  to  a  progressbox.   The only
difference between a program box and a progress box  is  that  a
program  box  displays  an OK button (but only after the command
completes).

This dialog box is  used  to  display  the  piped  output  of  a
command.   After  the  command completes, the user can press the
ENTER key so that dialog will exit and the calling shell  script
can continue its operation.

If  three  parameters  are given, it displays the text under the
title, delineated from the scrolling file's contents.   If  only
two parameters are given, this text is omitted.

manual
# ==================================================================
. /usr/local/lib/dd/setup-vars
. /usr/local/lib/dd/setup-tempfile

ls -l > "$tempfile"
(
	while true
	do
		read -r text
		[[ -z "$text" ]] && break
		ls -ld "$text" || break
		sleep 0.1
	done < "$tempfile"
) | "$DIALOG" --title "PROGRAMBOX" "$@" --programbox 20 70

retval=$?

. /usr/local/lib/dd/read-result
