#!/usr/bin/env bash
# shellcheck disable=SC1091,SC2034,SC2188
# ==================================================================
# progressbox
# ==================================================================
# Dialog Dojo Dialog Box
#
# File:         progressbox
# Author:       Ragdata
# Date:         15/09/2023
# License:      MIT License
# Copyright:    Copyright © 2023 Darren (Ragdata) Poulton
# ==================================================================
<<manual
"
--progressbox text height width
--progressbox height width

A progressbox is similar to an tailbox, except that

a) rather than displaying the contents of a file,
   it displays the piped output of a command and

b) it will exit when it reaches the end of the file
   (there is no 'OK' button).

If  three  parameters  are given, it displays the text under the
title, delineated from the scrolling file's contents.   If  only
two parameters are given, this text is omitted.
"
manual
# ==================================================================
. /usr/local/lib/dd/setup-vars
. /usr/local/lib/dd/setup-tempfile

ls -l > "$tempfile"
(
	while true
	do
		read -r text
		[[ -z "$text" ]] && break
		ls -ld "$text" || break
		sleep 1
	done < "$tempfile"
) | "$DIALOG" --title "PROGRESSBOX" "$@" --progressbox 20 70

retval=$?

. /usr/local/lib/dd/read-result
