#!/usr/bin/env bash
# shellcheck disable=SC1091,SC2034,SC2188
# ==================================================================
# rangebox
# ==================================================================
# Dialog Dojo Dialog Box
#
# File:         rangebox
# Author:       Ragdata
# Date:         15/09/2023
# License:      MIT License
# Copyright:    Copyright © 2023 Darren (Ragdata) Poulton
# ==================================================================
<<manual

--rangebox text height width min-value max-value default-value

Allow the user to select from a range of values, e.g.,  using  a
slider.   The  dialog shows the current value as a bar (like the
gauge dialog).  Tabs or arrow keys move the cursor  between  the
buttons and the value.  When the cursor is on the value, you can
edit it by:

left/right :: cursor movement to select a digit to modify

+/- :: characters to increment/decrement the digit by one

0 through 9 :: to set the digit to the given value

Some keys are also recognized in all cursor positions:

home/end :: set the value to its maximum or minimum

pageup/pagedown :: increment the value so that the slider moves by one column

manual
# ==================================================================
. /usr/local/lib/dd/setup-vars

RESULT=$($DIALOG --ok-label "${OK_LABEL:-OK}" \
	--cancel-label "${CANCEL_LABEL:-Cancel}" \
	--backtitle "${DIALOG_BACKTITLE}" \
	--title "${DIALOG_TITLE}" --clear "$@" \
	--rangebox "${DIALOG_TEXT}" "${HEIGHT:-15}" "${WIDTH:-50}" "${MIN_VALUE:-0}" "${MAX_VALUE:-100}" "${DEFAULT_VALUE:-50}" 3>&1 1>&2 2>&3)

retval=$?

. /usr/local/lib/dd/read-result
