#!/usr/bin/env bash
# shellcheck disable=SC1091,SC2034,SC2188
# ==================================================================
# treeview
# ==================================================================
# Dialog Dojo Dialog Box
#
# File:         treeview
# Author:       Ragdata
# Date:         15/09/2023
# License:      MIT License
# Copyright:    Copyright © 2023 Darren (Ragdata) Poulton
# ==================================================================
<<manual



manual
# ==================================================================
. /usr/local/lib/dd/setup-vars



retval=$?

. /usr/local/lib/dd/read-result
