#!/usr/bin/env bash
# shellcheck disable=SC1091,SC2034,SC2188
# ==================================================================
# treeview
# ==================================================================
# Dialog Dojo Dialog Box
#
# File:         treeview
# Author:       Ragdata
# Date:         15/09/2023
# License:      MIT License
# Copyright:    Copyright © 2023 Darren (Ragdata) Poulton
# ==================================================================
<<manual
"
--treeview text height width list-height [ tag item status depth ] ...

Display data organized as a tree.  Each group of data contains a
tag,  the  text  to  display  for  the item, its status ('on' or
'off') and the depth of the item in the tree.

Only one item can be selected (like the radiolist).  The tag  is
not displayed.

On  exit,  the  tag  of the selected item is written to dialog's
output.
"
manual
# ==================================================================
. /usr/local/lib/dd/setup-vars

RESULT=$("$DIALOG" --ok-label "${OK_LABEL:-OK}" \
	--cancel-label "${CANCEL_LABEL:-Cancel}" \
	--backtitle "${DIALOG_BACKTITLE}" \
	--title "${DIALOG_TITLE}" --cr-wrap --clear "$@" \
	--treeview "${DIALOG_TEXT}" "${HEIGHT:-15}" "${WIDTH:-50}" "${LIST_HEIGHT:-5}" \
	"${DIALOG_ITEMS[@]}" 3>&1 1>&2 2>&3)
